# Generated by Django 4.2.5 on 2023-09-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_consumer',
            field=models.BooleanField(default=True),
        ),
    ]
