# Generated by Django 4.2.5 on 2023-09-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem_quantity_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_subscribed',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
