# Generated by Django 4.2.5 on 2023-09-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_options_alter_product_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
