# Generated by Django 4.2.5 on 2023-09-18 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_paid',
        ),
    ]
