# Generated by Django 4.2.5 on 2023-09-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_subscription_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_consumer',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
