# Generated by Django 4.2.5 on 2023-09-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderitem_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
