# Generated by Django 4.2.5 on 2023-09-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_orderitem_amount_paid_order_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='retour',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
