# Generated by Django 4.2.5 on 2023-09-28 03:46

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_slug_alter_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='store/image', validators=[store.validators.validate_file_size]),
        ),
    ]
